env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

name: Publish WorkFlows for ELDependenci develop

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        id: checkout-source
        uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: |
            17
            21
          distribution: 'adopt'
      - run: mvn --batch-mode -Dmaven.deploy.skip=true clean package
        name: build plugins
      - uses: actions/upload-artifact@v4
        name: 'upload plugins'
        with:
          name: 'plugins'
          path: 'outputs/'
      - uses: actions/upload-artifact@v4
        name: 'upload javadocs'
        with:
          name: 'javadocs'
          path: 'javadocs/'

  upload_github_pkg_snapshot:
    runs-on: ubuntu-latest
    needs: [build]
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: |
            17
            21
          distribution: 'adopt'
      - run: echo ::set-output name=version::$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        id: project
      - name: Publish package
        run: mvn --batch-mode clean deploy
        if: ${{ endsWith(steps.project.outputs.version, '-SNAPSHOT') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
