env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

name: Publish WorkFlows for ELDependenci feature/hotfix branch

on:
  push:
    branches:
      - '*/*'
      - '!master'
      - '!develop'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        id: checkout-source
        uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '18'
          distribution: 'adopt'
      - run: mvn --batch-mode -Dmaven.deploy.skip=true -Dmaven.javadoc.skip=true clean package
        name: build plugins
      - uses: actions/upload-artifact@v1
        name: 'upload plugins'
        with:
          name: 'plugins'
          path: 'outputs/'